POST http://localhost:5000/api/users
Content-Type: application/json

{
    "groupId":1,
    "firstName": "Bobi",
    "lastName": "Huos",
    "email": "po7645ii7@gmail.com",
    "passwordHush": "123",
    "birthday": "1987-08-26",
    "gender": "female"
}

GET http://localhost:5000/api/users?page=2&results=3

GET http://localhost:5000/api/users/2



DELETE http://localhost:5000/api/users/15


PATCH http://localhost:5000/api/users/2
Content-Type: application/json

{
    "firstName": "Nataddd",
    "lastName": "Yakovddd",
    "email": "yakrr88rr@gmail.com",
    "passwordHush": "999",
    "birthday": "1983-10-14",
    "gender": "female"
}


PUT http://localhost:5000/api/users/4
Content-Type: application/json

{
    "firstName": "Den",
    "lastName": "Denov",
    "email": "denoooo@gmail.com",
    "passwordHush": "1234",
    "birthday": "1983-10-23",
    "gender": "male"
}


GET http://localhost:5000/api/users/1/tasks